import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Download, ChevronLeft, ChevronRight, Database, ShieldCheck, ArrowUpRight, Building2, MapPin, TrendingUp } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import './globals.css';
import './six.css';

type Row = Record<string, any>;
const count = (n: unknown) => n == null ? 'Not available' : Number(n).toLocaleString('en-IN');
const rupees = (n: unknown) => n == null ? 'Not observed' : new Intl.NumberFormat('en-IN', {style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)/100);
const crore = (n: unknown) => n == null ? 'Not observed' : `₹${(Number(n)/1e9).toLocaleString('en-IN',{maximumFractionDigits:2})} cr`;
const percent = (n: unknown) => n == null ? 'Not available' : `${(Number(n)*100).toFixed(1)}%`;
const signals: [string,string][] = [['','All signals'],['open_over_one_year_flag','Open beyond one year'],['no_payment_three_months_flag','No payment observed after 3 months'],['pending_recommendation_45d_flag','Pending recommendation >45 days'],['sanction_delay_45d_flag','Sanction delay proxy >45 days'],['repeat_payment_report_flag','Repeated payment-report rows'],['high_cost_peer_flag','High historical peer amount'],['high_similarity_review_flag','Similar work descriptions'],['paid_over_sanction_flag','Payments above sanction'],['completion_over_sanction_flag','Completion amount above sanction'],['completion_without_payment_flag','Completion without payment evidence'],['description_changed_flag','Description differs at completion'],['recommendation_missing_flag','Recommendation row missing']];

async function get<T>(url: string, signal?: AbortSignal): Promise<T> {
  const response = await fetch(url,{signal}); const data = await response.json();
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
}
function useData<T>(url: string | null, revision=0) {
  const [data,setData]=useState<T|null>(null); const [error,setError]=useState('');
  useEffect(()=>{setData(null);setError('');if(!url)return;const abort=new AbortController();get<T>(url,abort.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return ()=>abort.abort()},[url,revision]);
  return {data,error};
}
function Pick({label,value,items,onChange}:{label:string,value:string,items:[string,string][],onChange:(v:string)=>void}) {
  const values=items.map(([value,label])=>({value:value||'__all',label}));
  return <label className="s6-pick"><span>{label}</span><Select items={values} value={value||'__all'} onValueChange={v=>onChange(v==='__all'?'':String(v))}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v.value} value={v.value}>{v.label}</SelectItem>)}</SelectContent></Select></label>;
}
function Pager({offset,total,onChange}:{offset:number,total:number,onChange:(n:number)=>void}) {
  return <div className="s6-pager"><span>{total ? `${count(offset+1)}–${count(Math.min(offset+50,total))} of ${count(total)}`:'No matching records'}</span><button disabled={!offset} onClick={()=>onChange(Math.max(0,offset-50))}><ChevronLeft size={16}/>Previous</button><button disabled={offset+50>=total} onClick={()=>onChange(offset+50)}>Next<ChevronRight size={16}/></button></div>;
}
function Status({error,loading}:{error:string,loading:boolean}) {return error?<p role="alert" className="s6-warning">{error}</p>:loading?<p role="status" className="s6-note">Loading local records…</p>:null;}
function DownloadLink({file,children}:{file:string,children:React.ReactNode}) {return <a className="s6-link" href={`/api/download/${file}`} download><Download size={15}/>{children}</a>;}

function WorkEvidence({id,onClose,onWork,onEntity}:{id:string|null,onClose:()=>void,onWork:(id:string)=>void,onEntity:(key:string,value:string)=>void}) {
  const detail=useData<Row>(id?`/api/work/${id}`:null);
  const [paymentOffset,setPaymentOffset]=useState(0);const [revision,setRevision]=useState(0);
  const payments=useData<Row>(id?`/api/table?kind=payments&work_id=${id}&offset=${paymentOffset}`:null);
  const reviews=useData<Row>(id?'/api/reviews':null,revision);
  const [note,setNote]=useState('');const [outcome,setOutcome]=useState('Needs evidence');const [saveState,setSaveState]=useState('');const [saving,setSaving]=useState(false);
  useEffect(()=>{setPaymentOffset(0);setNote('');setOutcome('Needs evidence');setSaveState('')},[id]);
  async function save() {
    if(!detail.data)return;setSaving(true);setSaveState('');
    try {const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:id,outcome,note,version:detail.data.version})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSaveState('Saved on this computer.');setRevision(r=>r+1);setNote('')}catch(e){setSaveState(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}
  }
  const w=detail.data?.work;
  return <Sheet open={!!id} onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="s6-sheet"><SheetHeader><SheetTitle>Work {id} · Evidence</SheetTitle><SheetDescription>Source-backed observations for investigation, not a finding of misuse.</SheetDescription></SheetHeader><div className="s6-evidence"><Status error={detail.error} loading={!w}/>{w&&<>
    <h2>{w.description || 'Description not supplied'}</h2><p>{w.ida_name} · {w.state}</p><div className="s6-inline"><button onClick={()=>onEntity('mp',w.mp_key)}>MP: {w.mp_name}<ArrowUpRight size={14}/></button><button onClick={()=>onEntity('ida',w.ida_key)}>Other authority works<ArrowUpRight size={14}/></button></div>
    <div className="s6-lifecycle">{[['Recommended',w.recommendation_date,w.in_recommended?'Source 03':'Date from sanction; source 03 row absent'],['Sanctioned',w.sanction_date,'Source 04'],['Reported complete',w.completion_date,'Source 05']].map(([name,date,source])=><div key={name}><strong>{name}</strong><span>{date||'Not observed'}</span><small>{source}</small></div>)}</div>
    <h3>Financial reconciliation</h3><dl className="s6-facts">{[['Recommended',w.recommended_amount_paise],['Sanctioned',w.sanction_amount_paise],['Successful payments (reported)',w.has_successful_payment_evidence?w.successful_payment_paise:null],['In-progress payments (not settled)',w.pending_payment_paise],['Completion actual amount',w.completion_actual_paise],['One-row-per-fingerprint sensitivity',w.has_successful_payment_evidence?w.unique_fingerprint_sensitivity_paise:null],['Completion actual less observed payments',w.completion_payment_gap_paise]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{rupees(value)}</dd></div>)}</dl>
    <p className="s6-note">Missing payments are not assumed to be zero in the real world. The fingerprint sensitivity retains one identical report row; it is not corrected expenditure. Completion and payment differences need invoices, taxes/retention and source-coverage checks.</p>
    <h3>Why this work is in the queue · {w.priority_score}/100</h3>{detail.data!.reasons.length?<ul className="s6-reasons">{detail.data!.reasons.map((r:Row)=><li key={r.rule}><strong>+{r.points} · {r.reason}</strong><span>{r.caution}</span></li>)}</ul>:<p>No active weighted rule. Routine does not mean verified issue-free.</p>}
    <p>Model atypicality percentile: <strong>{Number(w.isolation_percentile).toFixed(1)}</strong>. This separate full-snapshot model is neither fraud probability nor a forecast.</p>
    <h3>Historical cost comparison</h3><dl className="s6-facts"><div><dt>Reference</dt><dd>{w.peer_level} · {count(w.peer_count)} earlier-year works</dd></div><div><dt>Peer median</dt><dd>{w.peer_median_inr==null?'Not available':rupees(w.peer_median_inr*100)}</dd></div><div><dt>Amount / peer median</dt><dd>{w.cost_peer_ratio==null?'Not available':Number(w.cost_peer_ratio).toFixed(2)+'×'}</dd></div></dl><p className="s6-note">The current work and current financial year do not set the benchmark. Amount comparisons are not unit-cost estimates.</p>
    <h3>Source differences and evidence gaps</h3><p>Recommendation stage: {w.recommendation_stage_raw||'Not supplied'} · Sanction stage: {w.sanction_stage_raw||'Not supplied'} · Canonical lifecycle: {w.lifecycle}</p>{!!w.description_changed_flag&&<p className="s6-warning">Completion description differs: {w.completion_description_raw}</p>}{!!w.recommendation_missing_flag&&<p className="s6-warning">Sanction record retained despite missing recommendation-export row.</p>}<p>Completion attachment reference: {w.completion_attachment_id||'Not supplied'}. No photograph has been downloaded or verified.</p>
    <h3>Payment evidence</h3><Status error={payments.error} loading={!payments.data}/>{payments.data&&<><Table><TableHeader><TableRow>{['Date','Vendor','Amount','Status','Identical rows'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{payments.data.items.map((p:Row)=><TableRow key={p.source_record}><TableCell>{p.payment_date}</TableCell><TableCell><button className="s6-text" onClick={()=>onEntity('vendor',p.vendor_id)}>{p.vendor_name}</button><small>ID {p.vendor_id} · source record {p.source_record}</small></TableCell><TableCell>{rupees(p.amount_paise)}</TableCell><TableCell>{p.payment_status}</TableCell><TableCell>{p.same_fingerprint_count}</TableCell></TableRow>)}</TableBody></Table><Pager offset={paymentOffset} total={payments.data.total} onChange={setPaymentOffset}/></>}
    <h3>Similar-work candidates</h3><p className="s6-note">At most 100 connected candidates shown here. See the complete pair export for all edges.</p>{detail.data!.pairs.length?detail.data!.pairs.map((p:Row)=><button className="s6-pair-link" key={p.pair_id} onClick={()=>onWork(p.work_id_a===id?p.work_id_b:p.work_id_a)}>Work {p.work_id_a===id?p.work_id_b:p.work_id_a} · similarity {percent(p.similarity)}{p.number_conflict?' · number conflict':''}{p.continuation_cue?' · phase/extension cue':''}</button>):<p>No retained candidate. Candidate search is bounded and not exhaustive.</p>}
    <h3>Record your review</h3><Pick label="Disposition" value={outcome} onChange={setOutcome} items={['Needs evidence','Expected variation','Data issue','Substantiated issue'].map(v=>[v,v])}/><label className="s6-note-input">Evidence or next action<textarea maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the document checked, finding, or evidence still needed."/></label><button disabled={saving||!note.trim()} onClick={save}>{saving?'Saving…':'Save review locally'}</button><p role="status">{saveState}</p><Status error={reviews.error} loading={!reviews.data}/>{reviews.data?.history.filter((r:Row)=>r.record_key===id).slice().reverse().map((r:Row)=><div className="s6-review" key={r.id}><strong>{r.outcome}</strong><small>{r.created}</small><p>{r.note}</p></div>)}
    <details><summary>All {Object.keys(w).length} work fields and source row references</summary><dl className="s6-facts">{Object.entries(w).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value==null?'Not available':String(value)}</dd></div>)}</dl></details>
  </>}</div></SheetContent></Sheet>;
}

function Queue({open,entity,clearEntity}:{open:(id:string)=>void,entity:Row,clearEntity:()=>void}) {
  const options=useData<Row>('/api/options');const [state,setState]=useState('');const [year,setYear]=useState('');const [lifecycle,setLifecycle]=useState('');const [signal,setSignal]=useState('');const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [sort,setSort]=useState('priority_score');
  useEffect(()=>{const t=setTimeout(()=>setSearch(query),300);return()=>clearTimeout(t)},[query]);
  useEffect(()=>setOffset(0),[state,year,lifecycle,signal,search,sort,entity]);
  const args=new URLSearchParams({state,fy:year,lifecycle,signal,q:search,sort,offset:String(offset),...entity});const works=useData<Row>('/api/works?'+args);
  const summary=works.data?.summary;
  return <><div className="s6-section-head"><div><h1>Work investigation</h1><p>Follow recommendations, sanctions, completion and vendor payments in one record.</p></div><DownloadLink file="Work_Features.csv">Full feature dataset</DownloadLink></div>
    <div className="s6-filters"><label className="s6-search"><span>Search works</span><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Work ID, description, MP or authority"/></div></label><Pick label="State / UT" value={state} onChange={setState} items={[['','All states'],...(options.data?.states||[]).map((v:string)=>[v,v])]}/><Pick label="Sanction financial year" value={year} onChange={setYear} items={[['','All years'],...(options.data?.years||[]).map((v:string)=>[v,v])]}/><Pick label="Lifecycle" value={lifecycle} onChange={setLifecycle} items={[['','All lifecycles'],...['Not in sanction export','Sanctioned / open','Reported complete'].map(v=>[v,v] as [string,string])]}/><Pick label="Investigation signal" value={signal} onChange={setSignal} items={signals}/><Pick label="Sort descending" value={sort} onChange={setSort} items={[['priority_score','Rule priority'],['isolation_percentile','Model atypicality'],['sanction_amount_paise','Sanction amount'],['successful_payment_paise','Successful payments'],['sanction_age_days','Sanction age']]}/></div>
    {!!Object.keys(entity).length&&<p className="s6-scope">Connected-entity filter active: {Object.keys(entity).join(', ')} <button onClick={clearEntity}>Clear entity filter</button></p>}
    <Status error={works.error||options.error} loading={!works.data}/>{summary&&<><div className="s6-metrics">{[['Matching works',count(summary.total)],['Reported complete',count(summary.completions)],['Sanctioned amount',crore(summary.sanction_paise)],['Successful payments',crore(summary.successful_payment_paise)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="s6-note">Figures follow the filters above. {count(summary.open_over_year)} open beyond one year · {count(summary.no_payment_three_months)} without an observed payment after three months · {crore(summary.pending_payment_paise)} in progress, excluded from successful payments.</p>
    <Table className="s6-work-table"><TableHeader><TableRow>{['Work / purpose','MP / authority','Lifecycle','Sanctioned','Successful payments','Review priority'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{works.data!.items.map((w:Row)=><TableRow key={w.work_id}><TableCell><button className="s6-text" onClick={()=>open(w.work_id)}>#{w.work_id} · Open evidence<ArrowUpRight size={14}/></button><p>{w.description||'No description supplied'}</p><small>{w.activity_type}</small></TableCell><TableCell>{w.mp_name}<small>{w.ida_name}</small><small>{w.state}</small></TableCell><TableCell>{w.lifecycle}<small>{w.sanction_date||'No observed sanction'}</small></TableCell><TableCell>{rupees(w.sanction_amount_paise)}</TableCell><TableCell>{rupees(w.successful_payment_paise)}<small>Observed report sum</small></TableCell><TableCell><span className={`s6-band s6-${w.priority_band.toLowerCase()}`}>{w.priority_band} · {w.priority_score}</span><small>Model percentile {Number(w.isolation_percentile).toFixed(1)}</small><small>{w.data_quality_issue_count} data-quality issues</small></TableCell></TableRow>)}</TableBody></Table><Pager offset={offset} total={summary.total} onChange={setOffset}/></>}
  </>;
}

function Entities({inspect}:{inspect:(key:string,value:string)=>void}) {
  const [kind,setKind]=useState('mps');const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [focus,setFocus]=useState<Row|null>(null);
  const data=useData<Row>('/api/table?'+new URLSearchParams({kind,q:query,offset:String(offset)}));
  useEffect(()=>{setOffset(0);setFocus(null)},[kind,query]);
  return <><h1>Connected entities</h1><p>Full-extract profiles. These figures do not inherit work-queue filters.</p><div className="s6-inline"><Pick label="Entity" value={kind} onChange={setKind} items={[["mps","Members of Parliament"],["idas","District authorities"],["vendors","Vendors"]]}/><label>Search name<input className="s6-input" value={query} onChange={e=>setQuery(e.target.value)}/></label><DownloadLink file={kind==='mps'?'MP_Features.csv':kind==='idas'?'IDA_Features.csv':'Vendor_Features.csv'}>Entity dataset</DownloadLink></div><Status error={data.error} loading={!data.data}/>{data.data&&<><Table><TableHeader><TableRow>{['Entity','Connected works','Successful payments','Pending payments','Details'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{data.data.items.map((r:Row)=>{const key=r.mp_key||r.ida_key||r.vendor_id;return <TableRow key={key}><TableCell>{r.mp_name||r.ida_name||r.vendor_name}<small>{r.state||`Vendor ID ${r.vendor_id}`}</small></TableCell><TableCell>{count(r.work_count)}</TableCell><TableCell>{rupees(r.successful_payment_paise)}</TableCell><TableCell>{rupees(r.pending_payment_paise)}</TableCell><TableCell><button onClick={()=>setFocus(r)}>Profile</button><button onClick={()=>inspect(kind==='mps'?'mp':kind==='idas'?'ida':'vendor',key)}>Inspect works</button></TableCell></TableRow>})}</TableBody></Table><Pager offset={offset} total={data.data.total} onChange={setOffset}/></>}{focus&&<section className="s6-panel"><h2>{focus.mp_name||focus.ida_name||focus.vendor_name}</h2><p className="s6-note">Allocation ratios use the supplied limit snapshot, not a certified annual bank balance. Shared vendor names do not mean the same legal entity. Concentration is descriptive, not evidence of collusion.</p><dl className="s6-facts">{Object.entries(focus).filter(([k])=>k.toLowerCase()===k).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{k.endsWith('_paise')?rupees(v):k.endsWith('_ratio')?percent(v):v==null?'Not observed':String(v)}</dd></div>)}</dl></section>}</>;
}

function Pairs({open}:{open:(id:string)=>void}) {
  const [offset,setOffset]=useState(0);const data=useData<Row>(`/api/duplicates?offset=${offset}`);
  return <><div className="s6-section-head"><div><h1>Similar-work candidates</h1><p>Compare both records. Matching descriptions do not establish duplicate assets.</p></div><DownloadLink file="Duplicate_Candidates.csv">All candidate pairs</DownloadLink></div><Status error={data.error} loading={!data.data}/>{data.data&&<><Table><TableHeader><TableRow>{['First work','Second work','Similarity','Cautions'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data.data.items.map((p:Row)=><TableRow key={p.pair_id}><TableCell><button onClick={()=>open(p.work_id_a)}>Work {p.work_id_a}</button><p>{p.description_a}</p><small>{rupees(p.amount_a)}</small></TableCell><TableCell><button onClick={()=>open(p.work_id_b)}>Work {p.work_id_b}</button><p>{p.description_b}</p><small>{rupees(p.amount_b)}</small></TableCell><TableCell>{percent(p.similarity)}</TableCell><TableCell>{[p.number_conflict?'Different number tokens':'',p.continuation_cue?'Phase/repair cue':'',p.generic_text?'Generic text':''].filter(Boolean).join(' · ')||'Location and scope still need verification'}</TableCell></TableRow>)}</TableBody></Table><Pager offset={offset} total={data.data.total} onChange={setOffset}/></>}<p className="s6-note">Bounded same-authority/activity matching, three rare-token anchors and at most three retained earlier matches per work. Cross-authority pairs and matches outside candidate windows may be missed. No measured real duplicate recall.</p></>;
}

function Validation() {
  const data=useData<Row>('/api/validation');const [budget,setBudget]=useState('0.2');
  const result=data.data?.budgets.find((r:Row)=>String(r.fraction)===budget);
  return <><h1>Offline A/B validation</h1><p>Equal-capacity baseline and enhanced screening. Controlled evidence injections are not fraud labels or a live trial.</p><Status error={data.error} loading={!data.data}/>{data.data&&<><p className="s6-note">{data.data.design}</p><Pick label="Review capacity" value={budget} onChange={setBudget} items={['0.05','0.1','0.2','0.3'].map(v=>[v,percent(v)])}/>{result&&<><div className="s6-metrics"><div><span>Baseline A recovery</span><strong>{percent(result.a_recovery)}</strong></div><div><span>Enhanced B recovery</span><strong>{percent(result.b_recovery)}</strong></div><div><span>Difference</span><strong>{(result.difference*100).toFixed(1)} pp</strong></div><div><span>Paired 95% interval</span><strong>{(result.ci95[0]*100).toFixed(1)} to {(result.ci95[1]*100).toFixed(1)} pp</strong></div></div><Table><TableHeader><TableRow>{['Injected scenario','Assigned cases','A recovered','B recovered'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{result.scenarios.map((r:Row)=><TableRow key={r.scenario}><TableCell>{r.scenario}</TableCell><TableCell>{r.assigned}</TableCell><TableCell>{r.a_selected}</TableCell><TableCell>{r.b_selected}</TableCell></TableRow>)}</TableBody></Table><p>Actual held-out queue overlap: {percent(result.actual_queue_overlap)}. Overlap describes different selections, not correctness.</p></>}<div className="s6-inline"><DownloadLink file="AB_Report.md">Methods and results</DownloadLink><DownloadLink file="ab_actual_scores.csv">Real held-out scores</DownloadLink><DownloadLink file="ab_controlled_benchmark.csv">Controlled benchmark</DownloadLink></div><ul>{data.data.limitations.map((v:string)=><li key={v}>{v}</li>)}</ul></> }</>;
}

function Sources({meta}:{meta:Row}) {
  const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const dictionary=useData<Row>('/api/table?'+new URLSearchParams({kind:'dictionary',q:query,offset:String(offset)}));const months=useData<Row>('/api/months');
  useEffect(()=>setOffset(0),[query]);
  return <><h1>Sources, features and research</h1><p>{meta.scope}. Assessment date {meta.as_of}; source extraction timestamps were not supplied.</p><Table><TableHeader><TableRow>{['Source','Original records','Accepted','Quarantined'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{meta.sources.map((r:Row)=><TableRow key={r.file}><TableCell>{r.file}<details><summary>SHA-256</summary><code>{r.sha256}</code></details></TableCell><TableCell>{count(r.rows)}</TableCell><TableCell>{count(r.accepted_rows)}</TableCell><TableCell>{r.quarantined_rows}</TableCell></TableRow>)}</TableBody></Table><p className="s6-warning">One expenditure record is truncated. Repeated payment fingerprints remain in reported sums. Missing documents or payments do not establish ghost assets, misuse or unpaid liabilities.</p><div className="s6-inline"><DownloadLink file="audit.json">Audit and source hashes</DownloadLink><DownloadLink file="Quarantine.csv">Quarantined record</DownloadLink><DownloadLink file="MPLADS_Six_Source_Review.xlsx">Plain Excel review</DownloadLink></div>
    <h2>Monthly payment observations</h2><p>Full extract. Successful and in-progress amounts are shown separately; no conclusion about waste is inferred from March spending.</p>{months.data&&<div className="s6-months"><Table><TableHeader><TableRow><TableHead>Month</TableHead><TableHead>Successful payments</TableHead><TableHead>In progress</TableHead></TableRow></TableHeader><TableBody>{months.data.items.map((m:Row)=><TableRow key={m.payment_month}><TableCell>{m.payment_month}</TableCell><TableCell>{rupees(m.successful_payment_paise)}</TableCell><TableCell>{rupees(m.pending_payment_paise)}</TableCell></TableRow>)}</TableBody></Table></div>}
    <h2>Evidence limits</h2><ul>{meta.limits.map((v:string)=><li key={v}>{v}</li>)}</ul><h2>Research used in the design</h2>{meta.research.map((r:Row)=><p key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a> · {r.date}<br/>{r.use}</p>)}
    <h2>Feature dictionary</h2><div className="s6-inline"><label>Search a field<input className="s6-input" value={query} onChange={e=>setQuery(e.target.value)}/></label><DownloadLink file="Feature_Dictionary.csv">Complete dictionary</DownloadLink></div><Status error={dictionary.error} loading={!dictionary.data}/>{dictionary.data&&<><Table><TableHeader><TableRow>{['Table / field','Definition','Unit / availability'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{dictionary.data.items.map((r:Row)=><TableRow key={r.table+r.field}><TableCell>{r.table}<small>{r.field}</small></TableCell><TableCell>{r.definition}</TableCell><TableCell>{r.unit}<small>{r.availability}</small></TableCell></TableRow>)}</TableBody></Table><Pager total={dictionary.data.total} offset={offset} onChange={setOffset}/></>}
  </>;
}

const COHORT_LABEL: Record<string,string> = {lok_sabha:'Lok Sabha', rs_sitting:'Rajya Sabha (sitting)', rs_retired:'Rajya Sabha (retired)'};
const heat = (frac: number) => `hsl(${Math.round(12 + 96 * Math.max(0, 1 - frac / 0.09))} 82% ${Math.round(94 - 34 * Math.min(1, frac / 0.09))}%)`;
const normState = (s: string) => s.toLowerCase().replace(/&/g,'and').replace(/[^a-z ]/g,' ').replace(/\b(the|island|islands)\b/g,' ').replace(/\s+/g,' ').trim();
const aliasState = (n: string) => (n.includes('dadra')||n.includes('daman'))?'dadra daman':n==='orissa'?'odisha':n==='uttaranchal'?'uttarakhand':n==='pondicherry'?'puducherry':n;
const stateKey = (s: string) => aliasState(normState(s));

function Choropleth({states,selected,onPick}:{states:Row[],selected:string,onPick:(s:string)=>void}) {
  const geo=useData<Row>('/india-states.geojson');
  const [hover,setHover]=useState<Row|null>(null);
  const byKey=new Map(states.map(s=>[stateKey(s.state),s]));
  const view=(()=>{
    const g=geo.data;if(!g)return null;
    let minx=1e9,miny=1e9,maxx=-1e9,maxy=-1e9;
    for(const f of g.features)for(const poly of f.geometry.coordinates)for(const ring of poly)for(const p of ring){if(p[0]<minx)minx=p[0];if(p[0]>maxx)maxx=p[0];if(p[1]<miny)miny=p[1];if(p[1]>maxy)maxy=p[1];}
    const W=440,sx=W/(maxx-minx),H=(maxy-miny)*sx;
    const paths=g.features.map((f:Row)=>{let d='';for(const poly of f.geometry.coordinates){for(const ring of poly){ring.forEach((p:number[],i:number)=>{d+=(i?'L':'M')+((p[0]-minx)*sx).toFixed(1)+' '+((maxy-p[1])*sx).toFixed(1);});d+='Z';}}return {geo:f.properties.state,row:byKey.get(stateKey(f.properties.state)),d};});
    return {W,H,paths};
  })();
  return <section className="s6-panel"><h3><MapPin size={16}/> State risk map</h3><p className="s6-note">Shaded by share of works in the High band. Hover for detail; click a state to see its district authorities. Telangana and Ladakh have no separate boundary in the base map and are not shaded.</p>
    <Status error={geo.error} loading={!geo.data}/>
    {view&&<div className="s6-mapwrap"><svg viewBox={`0 0 ${view.W} ${view.H}`} className="s6-map" role="img" aria-label="India state risk choropleth">{view.paths.map((p:Row)=>{const r=p.row;const f=r?r.high/r.works:null;const on=r&&selected===r.state;return <path key={p.geo} d={p.d} fill={f==null?'#e6eaee':heat(f)} stroke={on?'#0f2233':'#9fb0be'} strokeWidth={on?1.4:0.4} style={{cursor:r?'pointer':'default'}} onMouseEnter={()=>setHover(r||{state:p.geo,_nomatch:true})} onMouseLeave={()=>setHover(null)} onClick={()=>r&&onPick(selected===r.state?'':r.state)}/>;})}</svg>
      <div className="s6-maplegend"><span>Lower</span><i style={{background:heat(0)}}/><i style={{background:heat(0.03)}}/><i style={{background:heat(0.05)}}/><i style={{background:heat(0.07)}}/><i style={{background:heat(0.09)}}/><span>Higher High-band share</span></div>
      {hover&&<div className="s6-maptip">{hover._nomatch?<><strong>{hover.state}</strong><span>No matching works in this extract</span></>:<><strong>{hover.state}</strong><span>{count(hover.works)} works · {count(hover.high)} High ({(hover.high/hover.works*100).toFixed(1)}%)</span><span>{crore(hover.sanction_paise)} sanctioned</span></>}</div>}</div>}
  </section>;
}

function Overview({inspect}:{inspect:(key:string,value:string)=>void}) {
  const [state,setState]=useState('');
  const data=useData<Row>('/api/overview'+(state?`?state=${encodeURIComponent(state)}`:''));
  const months=useData<Row>('/api/months');
  const n=data.data?.national;
  const settledFrac=(r:Row)=>r.sanction_paise>0?r.successful_payment_paise/r.sanction_paise:null;
  const topStates=(data.data?.states||[]).slice(0,10).map((s:Row)=>({name:s.state.length>12?s.state.slice(0,11)+'…':s.state,High:s.high}));
  const trend=(months.data?.items||[]).map((m:Row)=>({month:m.payment_month,Settled:Math.round(m.successful_payment_paise/1e7)/100}));
  const d=data.data;const idas=state?d?.idas:d?.top_idas;
  return <><div className="s6-section-head"><div><h1>Decision-support overview</h1><p>National, state and authority risk at a glance. Bands and counts are review signals, never findings of fraud.</p></div><DownloadLink file="audit.json">National audit</DownloadLink></div>
    <Status error={data.error} loading={!n}/>{n&&<>
    <div className="s6-kpis">{[['Connected works',count(n.works)],['High-priority reviews',count(n.high)],['Sanctioned',crore(n.sanction_paise)],['Settled (reported)',crore(n.successful_payment_paise)],['Settled / sanctioned',percent(settledFrac(n))],['Open beyond one year',count(n.open_over_year)],['Members with works',count(n.mp_count)],['District authorities',count(n.ida_count)]].map(([label,value])=><div key={label} className="s6-kpi"><span>{label}</span><strong>{value}</strong></div>)}</div>

    <div className="s6-dash-cohorts">{(d!.cohorts||[]).map((c:Row)=><div key={c.cohort} className="s6-cohort"><header>{COHORT_LABEL[c.cohort]||c.cohort}</header><dl>{[['Works',count(c.works)],['High',count(c.high)],['Sanctioned',crore(c.sanction_paise)],['Settled/sanction',percent(settledFrac(c))]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>)}</div>

    <div className="s6-dash-grid">
      <section className="s6-panel"><h3><TrendingUp size={16}/> Top states by high-priority works</h3><div className="s6-chart"><ResponsiveContainer width="100%" height={220}><BarChart data={topStates} margin={{top:4,right:8,bottom:4,left:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0} angle={-30} textAnchor="end" height={54}/><YAxis tick={{fontSize:11}} allowDecimals={false}/><Tooltip/><Bar dataKey="High" fill="#c0392b" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></section>
      <section className="s6-panel"><h3><TrendingUp size={16}/> Monthly settled payments (₹ cr)</h3><div className="s6-chart"><ResponsiveContainer width="100%" height={220}><LineChart data={trend} margin={{top:4,right:8,bottom:4,left:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}} interval={Math.ceil(trend.length/8)}/><YAxis tick={{fontSize:11}}/><Tooltip/><Line dataKey="Settled" stroke="#2563eb" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div><p className="s6-note">Reported settlement timing only; no waste is inferred from year-end spending.</p></section>
    </div>

    <Choropleth states={d!.states} selected={state} onPick={setState}/>

    <section className="s6-panel"><h3><MapPin size={16}/> State risk heatmap</h3><p className="s6-note">Cell shade = share of works in the High band. Select a state to see its district authorities; use “Investigate” to open the filtered queue.</p>
      <div className="s6-heatwrap"><Table className="s6-heat"><TableHeader><TableRow>{['State / UT','Works','High','High %','Open &gt;1yr','Sanctioned','Settled/sanction','Mean priority',''].map(h=><TableHead key={h}>{h.replace('&gt;','>')}</TableHead>)}</TableRow></TableHeader><TableBody>{d!.states.map((s:Row)=>{const f=s.high/s.works;return <TableRow key={s.state} className={state===s.state?'s6-row-active':''}><TableCell><button className="s6-text" onClick={()=>setState(state===s.state?'':s.state)}>{s.state}</button></TableCell><TableCell>{count(s.works)}</TableCell><TableCell>{count(s.high)}</TableCell><TableCell><span className="s6-heatcell" style={{background:heat(f)}}>{(f*100).toFixed(1)}%</span></TableCell><TableCell>{count(s.open_over_year)}</TableCell><TableCell>{crore(s.sanction_paise)}</TableCell><TableCell>{percent(settledFrac(s))}</TableCell><TableCell>{Number(s.mean_priority).toFixed(1)}</TableCell><TableCell><button onClick={()=>inspect('state',s.state)}>Investigate<ArrowUpRight size={13}/></button></TableCell></TableRow>})}</TableBody></Table></div></section>

    <section className="s6-panel"><h3><Building2 size={16}/> {state?`District authorities · ${state}`:'Highest-risk district authorities (national top 20)'}</h3>{state&&<button className="s6-link" onClick={()=>setState('')}>Back to national top 20</button>}<Table><TableHeader><TableRow>{['Authority','State','Works','High','Open >1yr','Sanctioned','Settled','Investigate'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{(idas||[]).map((r:Row)=><TableRow key={r.ida_key}><TableCell>{r.ida_name}</TableCell><TableCell>{r.state}</TableCell><TableCell>{count(r.works)}</TableCell><TableCell>{count(r.high)}</TableCell><TableCell>{count(r.open_over_year)}</TableCell><TableCell>{crore(r.sanction_paise)}</TableCell><TableCell>{crore(r.successful_payment_paise)}</TableCell><TableCell><button onClick={()=>inspect('ida',r.ida_key)}>Works<ArrowUpRight size={13}/></button></TableCell></TableRow>)}</TableBody></Table></section>
    </>}</>;
}

function MPView({open}:{open:(id:string)=>void}) {
  const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [mp,setMp]=useState<Row|null>(null);
  useEffect(()=>{const t=setTimeout(()=>setSearch(query),300);return()=>clearTimeout(t)},[query]);
  const list=useData<Row>(mp?null:'/api/table?'+new URLSearchParams({kind:'mps',q:search}));
  const works=useData<Row>(mp?`/api/works?mp=${encodeURIComponent(mp.mp_key)}&sort=priority_score&order=desc`:null);
  const light=(m:Row)=>{const f=m.work_count?m.high_priority_count/m.work_count:0;return f>=0.06?['#c0392b','High attention']:f>=0.03?['#b8860b','Some attention']:['#2e7d32','Mostly routine'];};
  if(!mp){
    return <><div className="s6-section-head"><div><h1>Member of Parliament view</h1><p>Look up a member to see their allocation, utilisation, work progress and any flagged works. Signals are for review, not findings of fraud.</p></div></div>
      <label className="s6-search"><span>Search member by name</span><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="MP name"/></div></label>
      <Status error={list.error} loading={!list.data}/>{list.data&&<Table><TableHeader><TableRow>{['Member','State','Works','High-priority','Settled / allocation'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{list.data.items.map((m:Row)=><TableRow key={m.mp_key}><TableCell><button className="s6-text" onClick={()=>setMp(m)}>{m.mp_name}<ArrowUpRight size={14}/></button></TableCell><TableCell>{m.state}</TableCell><TableCell>{count(m.work_count)}</TableCell><TableCell>{count(m.high_priority_count)}</TableCell><TableCell>{percent(m.observed_paid_to_allocation_ratio)}</TableCell></TableRow>)}</TableBody></Table>}</>;
  }
  const [colour,label]=light(mp);
  return <><div className="s6-section-head"><div><h1>{mp.mp_name}</h1><p>{mp.constituency?mp.constituency+' · ':''}{mp.state}</p></div><button onClick={()=>{setMp(null);setQuery('')}}><ChevronLeft size={16}/>Back to search</button></div>
    <p className="s6-scope" style={{borderLeft:`5px solid ${colour}`}}><strong style={{color:colour}}>● {label}</strong> — {count(mp.high_priority_count)} of {count(mp.work_count)} works are in the High band. A traffic light summarises workload for review, not conduct.</p>
    <div className="s6-kpis">{[['Allocated (limit snapshot)',crore(mp.allocated_paise)],['Sanctioned',crore(mp.sanction_paise)],['Settled (reported)',crore(mp.successful_payment_paise)],['Settled / allocation',percent(mp.observed_paid_to_allocation_ratio)],['Sanction / allocation',percent(mp.sanction_to_allocation_ratio)],['Calamity consent',crore(mp.consented_paise)]].map(([l,v])=><div key={l} className="s6-kpi"><span>{l}</span><strong>{v}</strong></div>)}</div>
    <div className="s6-dash-grid">
      <section className="s6-panel"><h3>Work progress</h3><dl className="s6-facts">{[['Recommended records',count(mp.recommended_record_count)],['Sanctioned',count(mp.sanctioned_count)],['Completed',count(mp.completed_count)],['Completion / sanction',percent(mp.completion_to_sanction_ratio)],['Open beyond one year',count(mp.open_over_one_year_count)],['No payment after 3 months',count(mp.no_payment_three_months_count)]].map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></section>
      <section className="s6-panel"><h3>Compliance checks</h3><dl className="s6-facts"><div><dt>SC-area allocation (15% mandate)</dt><dd>Unavailable</dd></div><div><dt>ST-area allocation (7.5% mandate)</dt><dd>Unavailable</dd></div><div><dt>Trust/society ₹75L ceiling</dt><dd>Unavailable</dd></div><div><dt>Jurisdiction of recommendation</dt><dd>Unavailable</dd></div></dl><p className="s6-note">These mandates need beneficiary-area tags, a trust register and geocoding that are not in the supplied exports. They are shown as <strong>unavailable, not passed</strong>.</p></section>
    </div>
    <h3>Flagged and recent works</h3><Status error={works.error} loading={!works.data}/>{works.data&&<><Table className="s6-work-table"><TableHeader><TableRow>{['Work / purpose','Lifecycle','Sanctioned','Settled','Review priority'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{works.data.items.map((w:Row)=><TableRow key={w.work_id}><TableCell><button className="s6-text" onClick={()=>open(w.work_id)}>#{w.work_id} · Open evidence<ArrowUpRight size={14}/></button><p>{w.description||'No description supplied'}</p></TableCell><TableCell>{w.lifecycle}<small>{w.sanction_date||'No observed sanction'}</small></TableCell><TableCell>{rupees(w.sanction_amount_paise)}</TableCell><TableCell>{rupees(w.successful_payment_paise)}</TableCell><TableCell><span className={`s6-band s6-${w.priority_band.toLowerCase()}`}>{w.priority_band} · {w.priority_score}</span></TableCell></TableRow>)}</TableBody></Table><p className="s6-note">Showing the highest-priority works first (first {works.data.items.length} of {count(works.data.summary.total)}). Open a work for its full evidence trail.</p></>}</>;
}

function Ask({inspect}:{inspect:(key:string,value:string)=>void}) {
  const [draft,setDraft]=useState('');const [query,setQuery]=useState('');
  const data=useData<Row>('/api/ask'+(query?`?q=${encodeURIComponent(query)}`:''));
  const examples:string[]=data.data?.examples||[];
  const answered=!!data.data?.columns;
  const cell=(kind:string,v:unknown)=>kind==='money'?crore(v):kind==='pct'?percent(v):kind==='num'?(v==null?'—':Number(v).toFixed(1)):kind==='count'?count(v):(v==null?'—':String(v));
  return <><div className="s6-section-head"><div><h1>Ask the data</h1><p>Plain-English questions answered locally over the connected dataset. No external service; every figure is an aggregate of local rows shown with its exact query.</p></div></div>
    <form className="s6-ask" onSubmit={e=>{e.preventDefault();setQuery(draft.trim())}}><Search size={18}/><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="e.g. Which districts in Bihar have the most delays?"/><button type="submit" disabled={!draft.trim()}>Ask</button></form>
    <div className="s6-chips">{examples.map(x=><button key={x} className="s6-chip" onClick={()=>{setDraft(x);setQuery(x)}}>{x}</button>)}</div>
    <Status error={data.error} loading={!!query&&!data.data}/>
    {answered&&<section className="s6-panel"><p className="s6-note">Interpreted as: {data.data!.interpretation}</p><h3>{data.data!.summary}</h3>
      <div className="s6-heatwrap"><Table><TableHeader><TableRow>{data.data!.columns.map((c:Row)=><TableHead key={c.key}>{c.label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.data!.rows.map((r:Row,i:number)=><TableRow key={i}>{data.data!.columns.map((c:Row)=><TableCell key={c.key}>{c.key==='_dim'?<button className="s6-text" onClick={()=>{const k=data.data!.interpretation.toLowerCase();if(k.startsWith('state'))inspect('state',String(r._dim))}}>{cell(c.kind,r[c.key])}</button>:cell(c.kind,r[c.key])}</TableCell>)}</TableRow>)}</TableBody></Table></div>
      <p className="s6-note">{data.data!.caveat}</p>
      <details><summary>Generated SQL ({data.data!.row_count} rows)</summary><pre className="s6-sql">{data.data!.sql}{data.data!.params.length?`\n-- parameters: ${data.data!.params.join(', ')}`:''}</pre></details></section>}
  </>;
}

function App() {
  const meta=useData<Row>('/api/meta');const [tab,setTab]=useState('overview');const [selected,setSelected]=useState<string|null>(null);const [entity,setEntity]=useState<Row>({});
  function inspect(key:string,value:string){setEntity({[key]:value});setSelected(null);setTab('works')}
  const cohorts=(meta.data?.cohorts||[]).map((c:string)=>COHORT_LABEL[c]||c).join(' · ');
  return <div className="s6-app"><header className="s6-header"><div><Database size={24}/><strong>MPLADS Insight</strong><span>PS 26102 · Six-source investigation</span></div><span><ShieldCheck size={17}/>Local processing</span></header><div className="s6-context">{cohorts||'MPLADS'} · {meta.data?`${count(meta.data.totals.works)} connected works · as of ${meta.data.as_of}`:'Connecting to the local dataset'}<span>Review signals, not findings of fraud</span></div><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="s6-tabs">{[['overview','Overview'],['ask','Ask the data'],['works','Work investigation'],['mp','MP view'],['entities','MPs, authorities & vendors'],['pairs','Similar works'],['validation','A/B validation'],['sources','Data & research']].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList><main className="s6-main"><Status error={meta.error} loading={!meta.data}/>{meta.data&&<>{tab==='overview'&&<Overview inspect={inspect}/>} {tab==='ask'&&<Ask inspect={inspect}/>} {tab==='works'&&<Queue open={setSelected} entity={entity} clearEntity={()=>setEntity({})}/>} {tab==='mp'&&<MPView open={setSelected}/>} {tab==='entities'&&<Entities inspect={inspect}/>} {tab==='pairs'&&<Pairs open={setSelected}/>} {tab==='validation'&&<Validation/>} {tab==='sources'&&<Sources meta={meta.data}/>}</>}</main></Tabs><footer className="s6-footer">Local research prototype · No officer authentication or official audit certification. <a href="/api/reviews" target="_blank" rel="noreferrer">Export local review history</a></footer><WorkEvidence id={selected} onClose={()=>setSelected(null)} onWork={setSelected} onEntity={inspect}/></div>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
